Feature 9
DilshodMQ/BlogApp pull request #3
Opened 2022-10-07 05:33 UTC by DilshodMQ

Task-9

2022-10-07 16:33 UTC, napster1991 requested changes

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Admin/Controllers/PostsController.cs
> +            var posts=_context.Posts.Where(p=>p.StatusId == 2).ToList();
1. p.StatusId == 2 - bu nima digani? t.e. qaysi postlani bazadan obkevotti. chunarsiz. DilshodTni kodini bir ko'rin. Enum ishlatish kerak. o'shanda sizzi kodizzi o'qivotganlaga qulay bo'ladi
2. nega faqat 2ga teng bo'gan postlani ko'rsatvossiz? qoganlarinichi?

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Admin/Controllers/PostsController.cs
> +        public IActionResult Approve(int id)
bu action [HttpPost] bo'lishi kerak

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Admin/Controllers/PostsController.cs
> +            var post = _context.Posts.Include(p=>p.Status).FirstOrDefault(p=>p.Id == id);
agar post == null bo'lib qo'sa, nima bo'ladi?

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Admin/Controllers/PostsController.cs
> +            post.StatusId = 3;
StatusId uchun hamma joyda Enum ishlatin

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> +            var statuses=_context.Statuses.Take(2);
Create action ichida statuses kerak emas. t.e. viewga jo'natish kerak emas. siz postni statusini viewda set qimisiz baribir.

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> +        public async Task<IActionResult> Create(int statusId, [Bind("Title,Content")] PostCreateViewModel post)
bu action qanaqa bo'lishi kerakligini Dilshodni repositorysidan ko'rin

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> +            var statuses = _context.Statuses.Take(2);
betta ham shu. status faqat backendda set qilinadi

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> +            curPost.StatusId = statusId;
betta ham shu. Dilshodni kodini ko'rin

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> -        public async Task<IActionResult> DeleteConfirmed(int id)
bu methodni nega o'chirdiz?

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> -        private bool PostExists(int id)
bu ham qolishi kerak edi

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Users/Views/Posts/Create.cshtml
> +                @Html.DropDownList("statusId", ViewBag.Statuses as SelectList)
status frontendda set qilinmidi

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Users/Views/Posts/Details.cshtml
> +    @if(Model.StatusId!=2)
Enum ishlatish kerak

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Areas/Users/Views/Posts/Edit.cshtml
> +                @Html.DropDownList("statusId", ViewBag.Statuses as SelectList)
status frontendda set qilinmidi

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Controllers/HomeController.cs
> +            var posts = await _context.Posts.Where(p => p.StatusId == 3).ToListAsync();
ordering'ni ham, take'ni ham shu qatorni o'zida yozsa bo'ladi. DilshodTni kodini ko'rin.

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Models/Post.cs
> +        public int StatusId { get; set; }
bu porperty ForeginKey'ligini bildirib qo'yish kerak. DilshodTni ko'dini ko'rin

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Models/RoleEdit.cs
> +        public class RoleEdit
bu model nega kerak?

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Models/RoleModification.cs
> +    public class RoleModification
bu class nega kerak?

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Views/Shared/_Layout.cshtml
> +                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Posts" asp-action="Index"> Admin</a>
bu ssilka faqat adminga ko'rinishi kerak

2022-10-07 16:33 UTC, napster1991 commented on MvcApp/MvcApp/Views/Shared/_Layout.cshtml
>                              <a class="nav-link text-dark" asp-area="Users" asp-controller="Posts" asp-action="Index"> My Posts</a>
bu ssilka faqat userga ko'rinishi kerak

2022-10-11 01:41 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Admin/Controllers/PostsController.cs
> +        public IActionResult Approve(int id)
To`g`riladim

2022-10-11 01:44 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Admin/Controllers/PostsController.cs
> +            var post = _context.Posts.Include(p=>p.Status).FirstOrDefault(p=>p.Id == id);
Togriladim

2022-10-11 01:47 UTC, DilshodMQ commented on MvcApp/MvcApp/Models/RoleEdit.cs
> +        public class RoleEdit
Role qoshishni shunaqa yozmoqchi edim. qolib ketibdi. ochirdim.

2022-10-11 01:47 UTC, DilshodMQ commented on MvcApp/MvcApp/Models/RoleModification.cs
> +    public class RoleModification
Role qoshishni shunaqa yozmoqchi edim. qolib ketibdi. ochirdim.

2022-10-11 01:48 UTC, DilshodMQ commented on MvcApp/MvcApp/Views/Shared/_Layout.cshtml
> +                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Posts" asp-action="Index"> Admin</a>
Togriladim

2022-10-11 01:48 UTC, DilshodMQ commented on MvcApp/MvcApp/Views/Shared/_Layout.cshtml
>                              <a class="nav-link text-dark" asp-area="Users" asp-controller="Posts" asp-action="Index"> My Posts</a>
Togriladim

2022-10-11 01:51 UTC, DilshodMQ commented on MvcApp/MvcApp/Models/Post.cs
> +        public int StatusId { get; set; }
Attribut qo`shib qo`ydim

2022-10-11 09:56 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Admin/Controllers/PostsController.cs
> +            var posts=_context.Posts.Where(p=>p.StatusId == 2).ToList();
Ozgartirdim

2022-10-11 10:00 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Admin/Controllers/PostsController.cs
> +            post.StatusId = 3;
togriladim

2022-10-11 10:01 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> +            var statuses=_context.Statuses.Take(2);
togriladim

2022-10-11 10:21 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> +        public async Task<IActionResult> Create(int statusId, [Bind("Title,Content")] PostCreateViewModel post)
togriladim

2022-10-11 10:27 UTC, DilshodMQ commented on MvcApp/MvcApp/Controllers/HomeController.cs
> +            var posts = await _context.Posts.Where(p => p.StatusId == 3).ToListAsync();
togriladim

2022-10-11 10:36 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Users/Views/Posts/Details.cshtml
> +    @if(Model.StatusId!=2)
togriladim

2022-10-11 10:46 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> +            var statuses = _context.Statuses.Take(2);
togriladim

2022-10-11 10:48 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Users/Views/Posts/Edit.cshtml
> +                @Html.DropDownList("statusId", ViewBag.Statuses as SelectList)
togriladim

2022-10-11 10:49 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Users/Views/Posts/Create.cshtml
> +                @Html.DropDownList("statusId", ViewBag.Statuses as SelectList)
togriladim

2022-10-11 10:51 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> +            curPost.StatusId = statusId;
togriladim

2022-10-11 10:54 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> -        public async Task<IActionResult> DeleteConfirmed(int id)
qaytardim joyiga

2022-10-11 10:54 UTC, DilshodMQ commented on MvcApp/MvcApp/Areas/Users/Controllers/PostsController.cs
> -        private bool PostExists(int id)
buni ham qaytardim

2022-10-11 17:19 UTC, napster1991 approved these changes

2022-10-12 03:55 UTC, merged