Feature 15
DilshodMQ/BlogApp pull request #7
Opened 2022-10-18 11:46 UTC by DilshodMQ

2022-10-18 12:50 UTC, napster1991 requested changes

2022-10-18 12:50 UTC, napster1991 commented on MvcApp/MvcApp.Core/Services/Posts/UserPostService.cs
> +        public Post Details(int id)
oldingi safar ko'rmi qomman: mana bu method nega kerak? Base'da GetById bor-ku uje...

2022-10-18 12:50 UTC, napster1991 commented on MvcApp/MvcApp/Services/Posts/BasePostService.cs
>          {
service classlar sizda 2ta projectda ham bo'lib qobti 
![image](https://user-images.githubusercontent.com/11972414/196433980-b902f8e2-34b6-4d24-aaa6-4da0a8859aed.png)

2022-10-18 15:09 UTC, DilshodMQ commented on MvcApp/MvcApp/Services/Posts/BasePostService.cs
>          {
qolib ketgan ekan ochirdim

2022-10-18 15:11 UTC, DilshodMQ commented on MvcApp/MvcApp.Core/Services/Posts/UserPostService.cs
> +        public Post Details(int id)
Bu methoddan userga faqat  o`zining postlarini korsatish uchun foydalanganman

2022-10-19 05:12 UTC, napster1991 approved these changes

2022-10-19 10:29 UTC, merged